Repository andresagab/evet-check, pull requests merged in 2023-11, with the labels that each got.

#2 v0.5.0 - Update Roles module
  app/Livewire/Admin/Roles/ManageRolePermissions.php
  app/Livewire/Admin/Roles/RolesTable.php
  app/Models/Permission.php
  app/Models/Role.php
  app/Models/User.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/components/buttons/circle-icon-button.blade.php
  resources/views/components/tables/dates-columns.blade.php
  resources/views/livewire/admin/roles/manage-role-permissions.blade.php
  resources/views/livewire/admin/roles/roles-table.blade.php
Labels: bug, documentation, enhancement

#3 v0.6.0 - Create Users module
  app/Http/Controllers/admin/UserController.php
  app/Livewire/Admin/Users/UserDelete.php
  app/Livewire/Admin/Users/UserForm.php
  app/Livewire/Admin/Users/UsersTable.php
  app/Livewire/Forms/Admin/Users/Frm.php
  app/Utils/Threads/FormThread.php
  app/Utils/Threads/TableThread.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/components/admin/users/data-card.blade.php
  resources/views/components/admin/users/form-card.blade.php
  resources/views/components/layouts/navbars/admin-navbar.blade.php
  resources/views/components/tables/dates-columns.blade.php
  resources/views/livewire/admin/roles/roles-table.blade.php
  resources/views/livewire/admin/users/user-delete.blade.php
  resources/views/livewire/admin/users/user-form.blade.php
  resources/views/livewire/admin/users/users-table.blade.php
  resources/views/pages/admin/users/index.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#5 Add Permissions Module
  app/Http/Controllers/admin/PermissionController.php
  app/Livewire/Admin/Permissions/PermissionDelete.php
  app/Livewire/Admin/Permissions/PermissionForm.php
  app/Livewire/Admin/Permissions/PermissionsTable.php
  app/Livewire/Forms/Admin/Permissions/Frm.php
  app/Models/Permission.php
  resources/views/components/admin/permissions/data-card.blade.php
  resources/views/components/admin/permissions/form-card.blade.php
  resources/views/components/layouts/navbars/admin-navbar.blade.php
  resources/views/livewire/admin/permissions/permission-delete.blade.php
  resources/views/livewire/admin/permissions/permission-form.blade.php
  resources/views/livewire/admin/permissions/permissions-table.blade.php
  resources/views/pages/admin/permissions/index.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#6 v0.9.0 - Create People module
  app/Http/Controllers/PersonController.php
  app/Http/Controllers/admin/UserController.php
  app/Livewire/Forms/Sys/People/Frm.php
  app/Livewire/Sys/People/PeopleTable.php
  app/Livewire/Sys/People/PersonDelete.php
  app/Livewire/Sys/People/PersonForm.php
  app/Models/Sys/Person.php
  config/admin/permissions.php
  database/migrations/2023_11_15_211127_create_people_table.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/components/layouts/navbars/sys-navbar.blade.php
  resources/views/components/sys/people/data-card.blade.php
  resources/views/components/sys/people/form-card.blade.php
  resources/views/livewire/sys/people/people-table.blade.php
  resources/views/livewire/sys/people/person-delete.blade.php
  resources/views/livewire/sys/people/person-form.blade.php
  resources/views/pages/sys/people/index.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#7 v0.10.0 - Create Events module
  app/Livewire/Forms/Admin/Users/Frm.php
  app/Livewire/Forms/Sys/Events/Frm.php
  app/Livewire/Sys/Events/EventDelete.php
  app/Livewire/Sys/Events/EventForm.php
  app/Livewire/Sys/Events/EventsTable.php
  app/Models/Permission.php
  app/Models/Sys/Event.php
  app/Utils/Threads/FormThread.php
  config/admin/permissions.php
  database/migrations/2023_11_18_222758_create_events_table.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/components/layouts/navbars/sys-navbar.blade.php
  resources/views/components/sys/events/data-card.blade.php
  resources/views/components/sys/events/form-card.blade.php
  resources/views/livewire/admin/permissions/permissions-table.blade.php
  resources/views/livewire/sys/events/event-delete.blade.php
  resources/views/livewire/sys/events/event-form.blade.php
  resources/views/livewire/sys/events/events-table.blade.php
  resources/views/pages/admin/permissions/index.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#9 v0.12.0 - Create Activities module
  app/Livewire/Forms/Sys/Activities/Frm.php
  app/Livewire/Sys/Activities/ActivitiesTable.php
  app/Livewire/Sys/Activities/ActivityDelete.php
  app/Livewire/Sys/Activities/ActivityForm.php
  app/Models/Permission.php
  app/Models/Sys/Activity.php
  config/admin/permissions.php
  database/migrations/2023_11_19_213538_create_activities_table.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/components/layouts/navbars/sys-navbar.blade.php
  resources/views/components/sys/activities/data-card.blade.php
  resources/views/components/sys/activities/form-card.blade.php
  resources/views/livewire/sys/activities/activities-table.blade.php
  resources/views/livewire/sys/activities/activity-delete.blade.php
  resources/views/livewire/sys/activities/activity-form.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#10 v0.13.0 - Create Activity Attendance module
  app/Http/Controllers/ActivityAttendanceController.php
  app/Livewire/Forms/Sys/Activities/Attendances/Frm.php
  app/Livewire/Sys/Activities/Attendances/AttendanceDelete.php
  app/Livewire/Sys/Activities/Attendances/AttendanceForm.php
  app/Livewire/Sys/Activities/Attendances/AttendanceTable.php
  app/Livewire/Sys/Events/Attendances/AttendancesTable.php
  app/Models/Permission.php
  app/Models/Sys/ActivityAttendance.php
  config/admin/permissions.php
  database/migrations/2023_11_20_195732_create_activity_attendances_table.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/livewire/sys/activities/attendances/attendance-delete.blade.php
  resources/views/livewire/sys/activities/attendances/attendance-form.blade.php
  resources/views/livewire/sys/activities/attendances/attendance-table.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#11 v0.14.0 - Create portal module
  app/Livewire/Forms/Sys/Activities/Frm.php
  app/Livewire/Forms/Sys/People/Frm.php
  app/Livewire/Portal/Activities.php
  app/Livewire/Portal/Dashboard.php
  app/Livewire/Portal/Home.php
  app/Models/Sys/Activity.php
  app/Models/Sys/Event.php
  app/Models/Sys/Person.php
  database/migrations/2023_11_15_211127_create_people_table.php
  database/migrations/2023_11_19_213538_create_activities_table.php
  lang/en/messages.php
  lang/es/messages.php
  resources/js/bootstrap.js
  resources/js/sweet/Sweet.js
  resources/views/components/layouts/pages/base-layout.blade.php
  resources/views/components/sys/activities/data-card.blade.php
  resources/views/components/sys/activities/form-card.blade.php
  resources/views/components/sys/people/form-card.blade.php
  resources/views/livewire/portal/activities.blade.php
  resources/views/livewire/portal/dashboard.blade.php
  resources/views/livewire/portal/home.blade.php
  resources/views/livewire/sys/activities/activities-table.blade.php
  resources/views/pages/portal/index.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#12 v0.15.0 - Update portal module
  app/Livewire/Portal/Activities.php
  app/Livewire/Portal/Dashboard.php
  app/Livewire/Portal/Home.php
  app/Livewire/Portal/VirtualCard.php
  app/Models/Sys/Person.php
  composer.json
  composer.lock
  lang/en/messages.php
  lang/es/messages.php
  public/assets/img/virtual_card_template.png
  resources/views/components/layouts/navbars/portal-nav.blade.php
  resources/views/components/layouts/navbars/portal-navbar.blade.php
  resources/views/components/layouts/pages/portal-layout.blade.php
  resources/views/livewire/portal/activities.blade.php
  resources/views/livewire/portal/dashboard.blade.php
  resources/views/livewire/portal/home.blade.php
  resources/views/livewire/portal/virtual-card.blade.php
  routes/web.php
Labels: bug, documentation, enhancement

#13 v0.16.0 and v0.17.0
  .env.example
  app/Livewire/Forms/Sys/Events/Attendances/Frm.php
  app/Livewire/Forms/Sys/Events/Frm.php
  app/Livewire/Portal/Activities.php
  app/Livewire/Portal/VirtualCard.php
  app/Livewire/Sys/Activities/ActivitiesTable.php
  app/Livewire/Sys/Activities/RegisterAttendance.php
  app/Livewire/Sys/Events/Attendances/AttendancesTable.php
  app/Models/Sys/Event.php
  app/Models/Sys/EventAttendance.php
  config/admin/permissions.php
  config/fortify.php
  config/jetstream.php
  database/migrations/2023_11_18_222758_create_events_table.php
  database/migrations/2023_11_19_144922_create_event_attendances_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/UserSeeder.php
  lang/en/messages.php
  lang/es/messages.php
  resources/views/components/sys/activities/data-card.blade.php
  resources/views/components/sys/activities/info-card.blade.php
  resources/views/components/sys/events/attendances/data-card.blade.php
  resources/views/components/sys/events/attendances/form-card.blade.php
  resources/views/components/sys/events/data-card.blade.php
  resources/views/components/sys/events/form-card.blade.php
  resources/views/livewire/portal/dashboard.blade.php
  resources/views/livewire/sys/activities/activities-table.blade.php
  resources/views/livewire/sys/activities/register-attendance.blade.php
  resources/views/livewire/sys/events/attendances/attendances-table.blade.php
  resources/views/livewire/sys/events/events-table.blade.php
  resources/views/pages/jet/auth/register.blade.php
Labels: bug, documentation, enhancement

#14 v0.18.0 Update Activity Attendance module
  app/Livewire/Forms/Sys/Activities/Attendances/Frm.php
  app/Livewire/Sys/Activities/Attendances/AttendanceDelete.php
  app/Livewire/Sys/Activities/Attendances/AttendanceForm.php
  app/Livewire/Sys/Activities/Attendances/AttendanceTable.php
  resources/views/components/sys/activities/attendances/data-card.blade.php
  resources/views/components/sys/activities/attendances/form-card.blade.php
  resources/views/livewire/sys/activities/activities-table.blade.php
  resources/views/livewire/sys/activities/attendances/attendance-delete.blade.php
  resources/views/livewire/sys/activities/attendances/attendance-form.blade.php
  resources/views/livewire/sys/activities/attendances/attendance-table.blade.php
Labels: bug, documentation, enhancement

#16 v1.0 - Version 1
  .env.example
  app/Livewire/Sys/Activities/RegisterAttendance.php
  app/Models/Sys/EventAttendance.php
  app/Models/Sys/Person.php
  database/seeders/ActivitySeeder.php
  resources/views/components/layouts/footers/portal-footer.blade.php
  resources/views/components/sys/activities/info-card.blade.php
  resources/views/livewire/portal/virtual-card.blade.php
  resources/views/livewire/sys/activities/activities-table.blade.php
  resources/views/livewire/sys/activities/register-attendance.blade.php
Labels: bug, documentation, enhancement

#17 v1.1.0 - Update RegisterAttendance component
  app/Livewire/Sys/Activities/RegisterAttendance.php
Labels: bug

#18 v1.1.2 - Update web.php file routes and fix jetstream components
  resources/views/components/jet/confirmation-modal.blade.php
  resources/views/components/jet/welcome.blade.php
  resources/views/pages/jet/api/api-token-manager.blade.php
  resources/views/pages/jet/auth/forgot-password.blade.php
  resources/views/pages/jet/auth/login.blade.php
  resources/views/pages/jet/auth/reset-password.blade.php
  resources/views/pages/jet/auth/two-factor-challenge.blade.php
  resources/views/pages/jet/auth/verify-email.blade.php
  resources/views/pages/jet/dashboard.blade.php
  resources/views/pages/jet/policy.blade.php
  resources/views/pages/jet/terms.blade.php
  resources/views/profile/delete-user-form.blade.php
  routes/web.php
Labels: bug

#19 v1.1.3 - Update web.php routes file
  app/Livewire/Admin/Permissions/PermissionsTable.php
  app/Livewire/Admin/Roles/RolesTable.php
  app/Livewire/Admin/Users/UsersTable.php
  routes/web.php
Labels: bug

#20 v1.1.4 - Update Activity Attendances module
  app/Livewire/Forms/Sys/Activities/Attendances/Frm.php
  app/Models/Sys/ActivityAttendance.php
  resources/views/livewire/portal/activities.blade.php
Labels: bug, documentation
